### PR TITLE
Detect Huawei P20

### PR DESCRIPTION
**Pull request by atomarch**

### CODE REVIEW

**Review by mralbean — CHANGES_REQUESTED** [review]
Was this tested with `npm test`?

**Comment by atomarch** [comment]
I just ran "npm install" followed by "npm test".  820 tests complete (all green), so I assume everything is ok?  Any other steps I should take?

**Comment by mralbean** [comment]
It'll be a little tricky merging this in to the main `ua-parser` repo since it depends on a PR currently in review(https://github.com/faisalman/ua-parser-js/pull/383).

What I'll probably do is just cherry-pick your commit on top of the existing `huaweiDevices` branch I have, then update the PR on the main repo. 

Feel free to merge this in with master now though! Thanks for adding this!

**Review by mralbean — APPROVED** [review]
Forgot to click approve

**Comment by atomarch** [comment]
Ok, I'll land now, thanks!

**Pull request merged**
